name: Build Scarlet Rust Toolchain

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-24.04-arm
            system: aarch64-linux
          - os: macos-14
            system: aarch64-darwin

    runs-on: ${{ matrix.os }}
    env:
      CACHIX_CACHE_NAME: ${{ vars.CACHIX_CACHE_NAME }}
      CACHIX_AUTH_TOKEN: ${{ secrets.CACHIX_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - uses: cachix/cachix-action@v15
        if: env.CACHIX_CACHE_NAME != '' && env.CACHIX_AUTH_TOKEN != ''
        with:
          name: ${{ env.CACHIX_CACHE_NAME }}
          authToken: '${{ env.CACHIX_AUTH_TOKEN }}'
          pushFilter: "(scarlet-rust-src-vendored|scarlet-rustc)-"

      - name: Build Scarlet LLVM
        run: nix build .#packages.${{ matrix.system }}.scarlet-llvm -L --accept-flake-config

      - name: Build toolchain
        run: nix build .#packages.${{ matrix.system }}.scarlet-rust-toolchain -L --accept-flake-config

      - name: Check toolchain
        run: nix flake check . --system ${{ matrix.system }} -L --accept-flake-config

